export const SPOONACULAR_RANDOM_RECIPE_API = process.env.REACT_APP_SPOONACULAR_RANDOM_RECIPE_API;

export const SPOONACULAR_RECIPE_API = process.env.REACT_APP_SPOONACULAR_RECIPE_API;

export const SPOONACULAR_API_KEY = process.env.REACT_APP_SPOONACULAR_API_KEY;

export const SPOONACULAR_RECIPE_INFO_API = process.env.REACT_APP_SPOONACULAR_RECIPE_INFO_API;